fragment CourseParts on Course {
  __typename
  title
  level
  sector
  duration
  tagline
  description
  heroImage
  featured
  whatYouLearn
  employerBenefits
  modules {
    __typename
    title
    slug
    duration
    videoUrl
    description
    resources
  }
}

fragment HomeParts on Home {
  __typename
  announcementText
  heroHeadline
  heroSubtext
  heroTrustLine1
  heroTrustLine2
  heroTrustLine3
  heroImage1
  heroImage2
  stats {
    __typename
    value
    suffix
    label
  }
  employers
  whyHeadline
  whySubtext
  whyImage1
  whyImage2
  features {
    __typename
    title
    desc
  }
  howHeadline
  howImage
  steps {
    __typename
    title
    desc
  }
  insightsHeadline
  insights {
    __typename
    tag
    title
    date
    read
    img
    href
  }
  dualHeadline
  dualSubtext
  employerCardHeadline
  employerCardSubtext
  employerCardImage
  employerBullets
  learnerCardHeadline
  learnerCardSubtext
  learnerCardImage
  learnerBullets
  ctaHeadline
  ctaSubtext
  ctaPhone
  ctaEmail
}
