//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  course: Course;
  courseConnection: CourseConnection;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCourseArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCourseConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CourseFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  course?: InputMaybe<CourseFilter>;
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Course | Home | Folder;

export type CourseModules = {
  __typename?: 'CourseModules';
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  videoUrl?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  resources?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Course = Node & Document & {
  __typename?: 'Course';
  title: Scalars['String']['output'];
  level?: Maybe<Scalars['String']['output']>;
  sector?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  whatYouLearn?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  employerBenefits?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  modules?: Maybe<Array<Maybe<CourseModules>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type CourseModulesFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  resources?: InputMaybe<StringFilter>;
};

export type CourseFilter = {
  title?: InputMaybe<StringFilter>;
  level?: InputMaybe<StringFilter>;
  sector?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  whatYouLearn?: InputMaybe<StringFilter>;
  employerBenefits?: InputMaybe<StringFilter>;
  modules?: InputMaybe<CourseModulesFilter>;
};

export type CourseConnectionEdges = {
  __typename?: 'CourseConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Course>;
};

export type CourseConnection = Connection & {
  __typename?: 'CourseConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CourseConnectionEdges>>>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  announcementText?: Maybe<Scalars['String']['output']>;
  heroHeadline?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  heroTrustLine1?: Maybe<Scalars['String']['output']>;
  heroTrustLine2?: Maybe<Scalars['String']['output']>;
  heroTrustLine3?: Maybe<Scalars['String']['output']>;
  ctaHeadline?: Maybe<Scalars['String']['output']>;
  ctaSubtext?: Maybe<Scalars['String']['output']>;
  ctaPhone?: Maybe<Scalars['String']['output']>;
  ctaEmail?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeFilter = {
  announcementText?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  heroTrustLine1?: InputMaybe<StringFilter>;
  heroTrustLine2?: InputMaybe<StringFilter>;
  heroTrustLine3?: InputMaybe<StringFilter>;
  ctaHeadline?: InputMaybe<StringFilter>;
  ctaSubtext?: InputMaybe<StringFilter>;
  ctaPhone?: InputMaybe<StringFilter>;
  ctaEmail?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateCourse: Course;
  createCourse: Course;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateCourseArgs = {
  relativePath: Scalars['String']['input'];
  params: CourseMutation;
};


export type MutationCreateCourseArgs = {
  relativePath: Scalars['String']['input'];
  params: CourseMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  course?: InputMaybe<CourseMutation>;
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  course?: InputMaybe<CourseMutation>;
  home?: InputMaybe<HomeMutation>;
};

export type CourseModulesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  resources?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type CourseMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['String']['input']>;
  sector?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  whatYouLearn?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  employerBenefits?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  modules?: InputMaybe<Array<InputMaybe<CourseModulesMutation>>>;
};

export type HomeMutation = {
  announcementText?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  heroTrustLine1?: InputMaybe<Scalars['String']['input']>;
  heroTrustLine2?: InputMaybe<Scalars['String']['input']>;
  heroTrustLine3?: InputMaybe<Scalars['String']['input']>;
  ctaHeadline?: InputMaybe<Scalars['String']['input']>;
  ctaSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaPhone?: InputMaybe<Scalars['String']['input']>;
  ctaEmail?: InputMaybe<Scalars['String']['input']>;
};

export type CoursePartsFragment = { __typename: 'Course', title: string, level?: string | null, sector?: string | null, duration?: string | null, tagline?: string | null, description?: string | null, heroImage?: string | null, featured?: boolean | null, whatYouLearn?: Array<string | null> | null, employerBenefits?: Array<string | null> | null, modules?: Array<{ __typename: 'CourseModules', title: string, slug?: string | null, duration?: string | null, videoUrl?: string | null, description?: string | null, resources?: Array<string | null> | null } | null> | null };

export type HomePartsFragment = { __typename: 'Home', announcementText?: string | null, heroHeadline?: string | null, heroSubtext?: string | null, heroTrustLine1?: string | null, heroTrustLine2?: string | null, heroTrustLine3?: string | null, ctaHeadline?: string | null, ctaSubtext?: string | null, ctaPhone?: string | null, ctaEmail?: string | null };

export type CourseQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CourseQuery = { __typename?: 'Query', course: { __typename: 'Course', id: string, title: string, level?: string | null, sector?: string | null, duration?: string | null, tagline?: string | null, description?: string | null, heroImage?: string | null, featured?: boolean | null, whatYouLearn?: Array<string | null> | null, employerBenefits?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, modules?: Array<{ __typename: 'CourseModules', title: string, slug?: string | null, duration?: string | null, videoUrl?: string | null, description?: string | null, resources?: Array<string | null> | null } | null> | null } };

export type CourseConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CourseFilter>;
}>;


export type CourseConnectionQuery = { __typename?: 'Query', courseConnection: { __typename?: 'CourseConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CourseConnectionEdges', cursor: string, node?: { __typename: 'Course', id: string, title: string, level?: string | null, sector?: string | null, duration?: string | null, tagline?: string | null, description?: string | null, heroImage?: string | null, featured?: boolean | null, whatYouLearn?: Array<string | null> | null, employerBenefits?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, modules?: Array<{ __typename: 'CourseModules', title: string, slug?: string | null, duration?: string | null, videoUrl?: string | null, description?: string | null, resources?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, announcementText?: string | null, heroHeadline?: string | null, heroSubtext?: string | null, heroTrustLine1?: string | null, heroTrustLine2?: string | null, heroTrustLine3?: string | null, ctaHeadline?: string | null, ctaSubtext?: string | null, ctaPhone?: string | null, ctaEmail?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, announcementText?: string | null, heroHeadline?: string | null, heroSubtext?: string | null, heroTrustLine1?: string | null, heroTrustLine2?: string | null, heroTrustLine3?: string | null, ctaHeadline?: string | null, ctaSubtext?: string | null, ctaPhone?: string | null, ctaEmail?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const CoursePartsFragmentDoc = gql`
    fragment CourseParts on Course {
  __typename
  title
  level
  sector
  duration
  tagline
  description
  heroImage
  featured
  whatYouLearn
  employerBenefits
  modules {
    __typename
    title
    slug
    duration
    videoUrl
    description
    resources
  }
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  announcementText
  heroHeadline
  heroSubtext
  heroTrustLine1
  heroTrustLine2
  heroTrustLine3
  ctaHeadline
  ctaSubtext
  ctaPhone
  ctaEmail
}
    `;
export const CourseDocument = gql`
    query course($relativePath: String!) {
  course(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CourseParts
  }
}
    ${CoursePartsFragmentDoc}`;
export const CourseConnectionDocument = gql`
    query courseConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CourseFilter) {
  courseConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CourseParts
      }
    }
  }
}
    ${CoursePartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      course(variables: CourseQueryVariables, options?: C): Promise<{data: CourseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseQueryVariables, query: string}> {
        return requester<{data: CourseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseQueryVariables, query: string}, CourseQueryVariables>(CourseDocument, variables, options);
      },
    courseConnection(variables?: CourseConnectionQueryVariables, options?: C): Promise<{data: CourseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseConnectionQueryVariables, query: string}> {
        return requester<{data: CourseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseConnectionQueryVariables, query: string}, CourseConnectionQueryVariables>(CourseConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/99b80054-1d77-4109-8c6b-7676356d37e5/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  